package com.example.tabataki

enum class Language { EN, DE, ES, FR, IT, TR, RU }

object AppStrings {
    private val strings = mapOf(
        Language.EN to mapOf(
            "timer" to "TABATAKI",
            "work" to "Work Time",
            "rest" to "Rest Time",
            "rounds" to "Rounds",
            "switch_manual" to "SWITCH TO MANUAL TIMER",
            "remove_ads" to "AD-FREE",
            "pro_on" to "COMMUNITY EDITION",
            "start" to "START",
            "stop" to "STOP",
            "pause" to "PAUSE",
            "resume" to "RESUME",
            "prepare" to "PREPARE",
            "work_phase" to "WORK",
            "rest_phase" to "REST",
            "days_tab" to "Days & Routines",
            "tabataki_tab" to "Tabataki",
            "workout_days" to "Workout Days",
            "no_days" to "No days created yet. Add one!",
            "unnamed" to "Unnamed",
            "new_day" to "Create new day",
            "edit_day" to "Edit day",
            "day_name" to "Name (e.g. Day 1 Upper Body)",
            "save" to "Save",
            "cancel" to "Cancel",
            "start_day" to "START DAY",
            "exercises_linked" to "Exercises linked",
            "no_exercises" to "No exercises in this day. Add one!",
            "new_ex" to "Create new exercise",
            "edit_ex" to "Edit exercise",
            "ex_name" to "Name (e.g. Push-ups)",
            "in_sec" to "in Seconds ▼",
            "in_min" to "in Minutes ▼",
            "sec" to "Seconds",
            "min" to "Minutes",
            "total_ex" to "Total Exercises:",
            "custom" to "Custom",
            "lang" to "Language:",
            "ex" to "Exercises",
            "round" to "Round",
            "feedback" to "Send Feedback",
            "lib_title" to "Exercise Library",
            "search_ph" to "Search (e.g. Chest, Biceps)",
            "no_ex_found" to "No exercises found",
            "focus_label" to "Focus: ",
            "read_more" to "Read more ▼",
            "create_ex_title" to "Create New Exercise",
            "ex_name_label" to "Exercise Name",
            "cat_label" to "Category (e.g. TENNIS)",
            "focus_input" to "Focus / Muscle Group",
            "desc_input" to "Description",
            "del_cat_title" to "Delete Category?",
            "del_cat_desc" to "Delete this category and ALL of its exercises? This cannot be undone."
        ),
        Language.DE to mapOf(
            "timer" to "TABATAKI",
            "work" to "Arbeitszeit",
            "rest" to "Pausenzeit",
            "rounds" to "Runden",
            "switch_manual" to "ZUM MANUELLEN TIMER",
            "remove_ads" to "WERBEFREI",
            "pro_on" to "COMMUNITY-VERSION",
            "start" to "START",
            "stop" to "STOP",
            "pause" to "PAUSE",
            "resume" to "WEITER",
            "prepare" to "BEREIT",
            "work_phase" to "WORK",
            "rest_phase" to "PAUSE",
            "days_tab" to "Tage & Übungen",
            "tabataki_tab" to "Tabataki",
            "workout_days" to "Trainingstage",
            "no_days" to "Noch keine Tage erstellt!",
            "unnamed" to "Unbenannt",
            "new_day" to "Neuen Tag erstellen",
            "edit_day" to "Tag bearbeiten",
            "day_name" to "Name (z.B. Oberkörper)",
            "save" to "Speichern",
            "cancel" to "Abbrechen",
            "start_day" to "TAG STARTEN",
            "exercises_linked" to "Übungen verknüpft",
            "no_exercises" to "Keine Übungen. Füge eine hinzu!",
            "new_ex" to "Neue Übung",
            "edit_ex" to "Übung bearbeiten",
            "ex_name" to "Name (z.B. Bankdrücken)",
            "in_sec" to "in Sekunden ▼",
            "in_min" to "in Minuten ▼",
            "sec" to "Sekunden",
            "min" to "Minuten",
            "total_ex" to "Übungen gesamt:",
            "custom" to "Manuell",
            "lang" to "Sprache:",
            "ex" to "Übungen",
            "round" to "Runde",
            "feedback" to "Feedback senden",
            "lib_title" to "Übungs-Bibliothek",
            "search_ph" to "Suchen (z.B. Brust, Bizeps)",
            "no_ex_found" to "Keine Übungen gefunden",
            "focus_label" to "Fokus: ",
            "read_more" to "Mehr lesen ▼",
            "create_ex_title" to "Neue Übung erstellen",
            "ex_name_label" to "Name der Übung",
            "cat_label" to "Kategorie (z.B. TENNIS)",
            "focus_input" to "Fokus / Zielmuskel",
            "desc_input" to "Erklärung",
            "del_cat_title" to "Kategorie löschen?",
            "del_cat_desc" to "Diese Kategorie und ALLE zugehörigen Übungen löschen? Das kann nicht rückgängig gemacht werden."
        ),
        Language.ES to mapOf(
            "timer" to "TABATAKI",
            "work" to "Trabajo",
            "rest" to "Descanso",
            "rounds" to "Rondas",
            "switch_manual" to "MANUAL",
            "remove_ads" to "SIN ANUNCIOS",
            "pro_on" to "EDICIÓN COMUNITARIA",
            "start" to "INICIAR",
            "stop" to "PARAR",
            "pause" to "PAUSA",
            "resume" to "REANUDAR",
            "prepare" to "PREPARAR",
            "work_phase" to "TRABAJO",
            "rest_phase" to "DESCANSO",
            "days_tab" to "Días y Rutinas",
            "tabataki_tab" to "Tabataki",
            "workout_days" to "Días de Entrenamiento",
            "no_days" to "¡Aún no hay días!",
            "unnamed" to "Sin nombre",
            "new_day" to "Crear nuevo día",
            "edit_day" to "Editar día",
            "day_name" to "Nombre (ej. Día 1)",
            "save" to "Guardar",
            "cancel" to "Cancelar",
            "start_day" to "INICIAR DÍA",
            "exercises_linked" to "Ejercicios vinculados",
            "no_exercises" to "Sin ejercicios. ¡Añade uno!",
            "new_ex" to "Crear ejercicio",
            "edit_ex" to "Editar ejercicio",
            "ex_name" to "Nombre (ej. Flexiones)",
            "in_sec" to "en Segundos ▼",
            "in_min" to "en Minutos ▼",
            "sec" to "Segundos",
            "min" to "Minutos",
            "total_ex" to "Ejercicios totales:",
            "custom" to "Personalizado",
            "lang" to "Idioma:",
            "ex" to "Ejercicios",
            "round" to "Ronda",
            "feedback" to "Enviar comentarios",
            "lib_title" to "Biblioteca de Ejercicios",
            "search_ph" to "Buscar (ej. Pecho, Bíceps)",
            "no_ex_found" to "No se encontraron ejercicios",
            "focus_label" to "Enfoque: ",
            "read_more" to "Leer más ▼",
            "create_ex_title" to "Crear Nuevo Ejercicio",
            "ex_name_label" to "Nombre del Ejercicio",
            "cat_label" to "Categoría (ej. TENIS)",
            "focus_input" to "Enfoque / Grupo Muscular",
            "desc_input" to "Descripción",
            "del_cat_title" to "¿Eliminar Categoría?",
            "del_cat_desc" to "¿Eliminar esta categoría y TODOS sus ejercicios? Esto no se puede deshacer."
        ),
        Language.FR to mapOf(
            "timer" to "TABATAKI",
            "work" to "Travail",
            "rest" to "Repos",
            "rounds" to "Séries",
            "switch_manual" to "MODE MANUEL",
            "remove_ads" to "SANS PUBLICITÉ",
            "pro_on" to "ÉDITION COMMUNAUTAIRE",
            "start" to "DÉMARRER",
            "stop" to "ARRÊTER",
            "pause" to "PAUSE",
            "resume" to "REPRENDRE",
            "prepare" to "PRÉPARER",
            "work_phase" to "TRAVAIL",
            "rest_phase" to "REPOS",
            "days_tab" to "Jours et Routines",
            "tabataki_tab" to "Tabataki",
            "workout_days" to "Jours d'Entraînement",
            "no_days" to "Pas encore de jours !",
            "unnamed" to "Sans nom",
            "new_day" to "Créer un jour",
            "edit_day" to "Modifier le jour",
            "day_name" to "Nom (ex. Jour 1)",
            "save" to "Enregistrer",
            "cancel" to "Annuler",
            "start_day" to "DÉMARRER",
            "exercises_linked" to "Exercices liés",
            "no_exercises" to "Aucun exercice.",
            "new_ex" to "Créer un exercice",
            "edit_ex" to "Modifier l'exercice",
            "ex_name" to "Nom (ex. Pompes)",
            "in_sec" to "en Secondes ▼",
            "in_min" to "en Minutes ▼",
            "sec" to "Secondes",
            "min" to "Minutes",
            "total_ex" to "Exercices totaux :",
            "custom" to "Personnalisé",
            "lang" to "Langue :",
            "ex" to "Exercices",
            "round" to "Série",
            "feedback" to "Envoyer vos remarques",
            "lib_title" to "Bibliothèque d'Exercices",
            "search_ph" to "Rechercher (ex. Pectoraux, Biceps)",
            "no_ex_found" to "Aucun exercice trouvé",
            "focus_label" to "Focus : ",
            "read_more" to "En savoir plus ▼",
            "create_ex_title" to "Créer un Nouvel Exercice",
            "ex_name_label" to "Nom de l'Exercice",
            "cat_label" to "Catégorie (ex. TENNIS)",
            "focus_input" to "Focus / Groupe Musculaire",
            "desc_input" to "Description",
            "del_cat_title" to "Supprimer la Catégorie ?",
            "del_cat_desc" to "Supprimer cette catégorie et TOUS ses exercices ? Action irréversible."
        ),
        Language.IT to mapOf(
            "timer" to "TABATAKI",
            "work" to "Lavoro",
            "rest" to "Riposo",
            "rounds" to "Round",
            "switch_manual" to "PASSA A MANUALE",
            "remove_ads" to "SENZA PUBBLICITÀ",
            "pro_on" to "EDIZIONE COMMUNITY",
            "start" to "INIZIA",
            "stop" to "FERMA",
            "pause" to "PAUSA",
            "resume" to "RIPRENDI",
            "prepare" to "PREPARATI",
            "work_phase" to "LAVORO",
            "rest_phase" to "RIPOSO",
            "days_tab" to "Giorni e Routine",
            "tabataki_tab" to "Tabataki",
            "workout_days" to "Giorni",
            "no_days" to "Nessun giorno creato!",
            "unnamed" to "Senza nome",
            "new_day" to "Crea nuovo giorno",
            "edit_day" to "Modifica giorno",
            "day_name" to "Nome",
            "save" to "Salva",
            "cancel" to "Annulla",
            "start_day" to "INIZIA GIORNO",
            "exercises_linked" to "Esercizi collegati",
            "no_exercises" to "Nessun esercizio.",
            "new_ex" to "Crea esercizio",
            "edit_ex" to "Modifica esercizio",
            "ex_name" to "Nome (es. Flessioni)",
            "in_sec" to "in Secondi ▼",
            "in_min" to "in Minuti ▼",
            "sec" to "Secondi",
            "min" to "Minuti",
            "total_ex" to "Esercizi totali:",
            "custom" to "Personalizzato",
            "lang" to "Lingua:",
            "ex" to "Esercizi",
            "round" to "Round",
            "feedback" to "Invia feedback",
            "lib_title" to "Libreria Esercizi",
            "search_ph" to "Cerca (es. Petto, Bicipiti)",
            "no_ex_found" to "Nessun esercizio trovato",
            "focus_label" to "Focus: ",
            "read_more" to "Leggi di più ▼",
            "create_ex_title" to "Crea Nuovo Esercizio",
            "ex_name_label" to "Nome dell'Esercizio",
            "cat_label" to "Categoria (es. TENNIS)",
            "focus_input" to "Focus / Gruppo Muscolare",
            "desc_input" to "Descrizione",
            "del_cat_title" to "Elimina Categoria?",
            "del_cat_desc" to "Eliminare questa categoria e TUTTI i suoi esercizi? Questa azione è irreversibile."
        ),
        Language.TR to mapOf(
            "timer" to "TABATAKI",
            "work" to "Çalışma",
            "rest" to "Dinlenme",
            "rounds" to "Raunt",
            "switch_manual" to "MANUELE GEÇ",
            "remove_ads" to "REKLAMSIZ",
            "pro_on" to "TOPLULUK SÜRÜMÜ",
            "start" to "BAŞLAT",
            "stop" to "DURDUR",
            "pause" to "DURAKLAT",
            "resume" to "DEVAM ET",
            "prepare" to "HAZIRLAN",
            "work_phase" to "ÇALIŞMA",
            "rest_phase" to "DİNLENME",
            "days_tab" to "Günler / Rutinler",
            "tabataki_tab" to "Tabataki",
            "workout_days" to "Antrenman Günleri",
            "no_days" to "Gün oluşturulmadı!",
            "unnamed" to "İsimsiz",
            "new_day" to "Yeni gün oluştur",
            "edit_day" to "Günü düzenle",
            "day_name" to "İsim (örn. Gün 1)",
            "save" to "Kaydet",
            "cancel" to "İptal",
            "start_day" to "GÜNÜ BAŞLAT",
            "exercises_linked" to "Egzersiz bağlı",
            "no_exercises" to "Egzersiz yok.",
            "new_ex" to "Egzersiz oluştur",
            "edit_ex" to "Egzersizi düzenle",
            "ex_name" to "İsim (örn. Şınav)",
            "in_sec" to "Saniye olarak ▼",
            "in_min" to "Dakika olarak ▼",
            "sec" to "Saniye",
            "min" to "Dakika",
            "total_ex" to "Toplam Egzersiz:",
            "custom" to "Özel",
            "lang" to "Dil:",
            "ex" to "Egzersizler",
            "round" to "Raunt",
            "feedback" to "Geri bildirim gönder",
            "lib_title" to "Egzersiz Kütüphanesi",
            "search_ph" to "Ara (örn. Göğüs, Biseps)",
            "no_ex_found" to "Egzersiz bulunamadı",
            "focus_label" to "Odak: ",
            "read_more" to "Daha fazla oku ▼",
            "create_ex_title" to "Yeni Egzersiz Oluştur",
            "ex_name_label" to "Egzersiz Adı",
            "cat_label" to "Kategori (örn. TENİS)",
            "focus_input" to "Odak / Kas Grubu",
            "desc_input" to "Açıklama",
            "del_cat_title" to "Kategoriyi Sil?",
            "del_cat_desc" to "Bu kategoriyi ve TÜM egzersizlerini sil? Bu işlem geri alınamaz."
        ),
        Language.RU to mapOf(
            "timer" to "TABATAKI",
            "work" to "Работа",
            "rest" to "Отдых",
            "rounds" to "Раунды",
            "switch_manual" to "РУЧНОЙ РЕЖИМ",
            "remove_ads" to "БЕЗ РЕКЛАМЫ",
            "pro_on" to "ВЕРСИЯ СООБЩЕСТВА",
            "start" to "СТАРТ",
            "stop" to "СТОП",
            "pause" to "ПАУЗА",
            "resume" to "ПРОДОЛЖИТЬ",
            "prepare" to "ПОДГОТОВКА",
            "work_phase" to "РАБОТА",
            "rest_phase" to "ОТДЫХ",
            "days_tab" to "Дни / Программы",
            "tabataki_tab" to "Tabataki",
            "workout_days" to "Тренировочные Дни",
            "no_days" to "Дни не созданы!",
            "unnamed" to "Без названия",
            "new_day" to "Создать день",
            "edit_day" to "Изменить день",
            "day_name" to "Название (напр. День 1)",
            "save" to "Сохранить",
            "cancel" to "Отмена",
            "start_day" to "НАЧАТЬ ДЕНЬ",
            "exercises_linked" to "Упражнения привязаны",
            "no_exercises" to "Нет упражнений. Добавь!",
            "new_ex" to "Создать упражнение",
            "edit_ex" to "Изменить упражнение",
            "ex_name" to "Название (напр. Отжимания)",
            "in_sec" to "в Секундах ▼",
            "in_min" to "в Минутах ▼",
            "sec" to "Секунды",
            "min" to "Минуты",
            "total_ex" to "Всего упражнений:",
            "custom" to "Свой вариант",
            "lang" to "Язык:",
            "ex" to "Упражнения",
            "round" to "Раунд",
            "feedback" to "Отправить отзыв",
            "lib_title" to "Библиотека Упражнений",
            "search_ph" to "Поиск (напр. Грудь, Бицепс)",
            "no_ex_found" to "Упражнения не найдены",
            "focus_label" to "Фокус: ",
            "read_more" to "Читать далее ▼",
            "create_ex_title" to "Создать Упражнение",
            "ex_name_label" to "Название Упражнения",
            "cat_label" to "Категория (напр. ТЕННИС)",
            "focus_input" to "Фокус / Целевая мышца",
            "desc_input" to "Описание"
        )
    )
    fun get(lang: Language, key: String): String {
        return strings[lang]?.get(key) ?: strings[Language.EN]?.get(key) ?: " "
    }
}
